/* js/proto.js — Screen map FAB. Cover/landing lives in screens-landing.js. */
function protoHTML() {
  return `<p class="proto-note">v1. Меню как в GitLab: закрепления + «Меню». Новый проект — чеклист запуска, потом статус «в работе».</p>
  <h4 class="h6">Дизайн</h4>
  <a href="#/lab/cards">Канон карточек</a>
  <a href="#/lab/page">Анатомия экрана</a>
  <h4 class="h6">Флоу</h4>
  <a href="#/">Лендинг MVP</a>
  <a href="#/login">Логин → проекты</a>
  <a href="#/projects/empty">Логин без проектов</a>
  <a href="#/p/omsk/overview">Другой проект через switcher (Омск)</a>
  <h4 class="h6">Auth</h4>
  <a href="#/login">Login</a>
  <a href="#/login/tfa">TFA</a>
  <a href="#/signup">Signup</a>
  <a href="#/password-reset">Сброс пароля</a>
  <a href="#/operator-blocked">Кабинет / оператор</a>
  <h4 class="h6">Projects</h4>
  <a href="#/projects">Сетка 8</a>
  <a href="#/projects/one">1 проект</a>
  <a href="#/projects/empty">Empty</a>
  <a href="#/projects/new">Новый проект · 3 пути</a>
  <a href="#/projects/new/preset">Пресеты</a>
  <a href="#/projects/new/wizard">Мастер</a>
  <a href="#/p/omsk/overview">Омск · сценарий на входе + AI на перезвон</a>
  <a href="#/p/wa/overview">WhatsApp · AI FAQ и сценарий возвратов</a>
  <h4 class="h6">Проект</h4>
  <a href="#/p/courier/overview">Обзор</a>
  <a href="#/p/courier/agents">AI-агенты</a>
  <a href="#/p/courier/agents/empty">AI-агенты empty</a>
  <a href="#/p/courier/agents/agt_7K2m">Карточка AI-агента</a>
  <a href="#/p/courier/bots">Сценарии</a>
  <a href="#/p/courier/bots/empty">Сценарии empty</a>
  <a href="#/p/courier/bots/bot_91qx">Карточка сценария</a>
  <a href="#/p/courier/nlu">NLU-модели</a>
  <a href="#/p/courier/nlu/nlu_hr1">Карточка NLU-модели</a>
  <a href="#/p/courier/calls">Звонки</a>
  <a href="#/p/courier/calls/empty">Звонки empty</a>
  <a href="#/p/courier/calls/job_44a">Задание</a>
  <a href="#/p/courier/calls/templates">Шаблоны заданий</a>
  <a href="#/p/courier/calls/history">Детализация</a>
  <a href="#/p/courier/calls/schedule">Расписание</a>
  <a href="#/p/courier/calls/blacklist">Чёрный список</a>
  <a href="#/p/courier/numbers">Номера</a>
  <a href="#/p/courier/numbers/shop">Витрина номеров</a>
  <a href="#/p/courier/knowledge">База знаний</a>
  <a href="#/p/courier/chats">Чаты</a>
  <a href="#/p/courier/chats/templates">Шаблоны чатов</a>
  <a href="#/p/courier/campaigns">Рассылки</a>
  <a href="#/p/courier/campaigns/templates">Шаблоны рассылок</a>
  <a href="#/p/courier/market">Маркетплейс</a>
  <a href="#/p/courier/integrations">Интеграции</a>
  <a href="#/p/courier/integrations/none">Интеграции empty</a>
  <a href="#/p/courier/integrations/telegram">Подключение</a>
  <a href="#/p/courier/analytics">Аналитика</a>
  <a href="#/p/courier/analytics/calls">Аналитика · звонки</a>
  <a href="#/p/courier/analytics/chats">Аналитика · чаты</a>
  <a href="#/p/courier/analytics/spend">Аналитика · расход</a>
  <a href="#/p/courier/analytics/reports">Отчёты</a>
  <a href="#/p/clinic/analytics/campaigns">Аналитика · рассылки (клиника)</a>
  <a href="#/p/courier/settings">Настройки</a>
  <a href="#/p/courier/settings/members">Участники</a>
  <a href="#/p/courier/settings/telephony">Телефония проекта</a>
  <h4 class="h6">Аккаунт</h4>
  <a href="#/account/company">Компания</a>
  <a href="#/account/billing">Биллинг</a>
  <a href="#/account/team">Команда</a>
  <h4 class="h6">States</h4>
  <a href="#/p/courier/loading">Skeleton</a>
  <a href="#/error">Ошибка</a>
  <a href="#/p/courier/404">Не найдено в проекте</a>
  <a href="#/p/courier/no-access">Нет доступа</a>`
}
